require 'activeadmin-orderable-table/version'
require 'active_record'
require 'active_record/railtie'
require 'rails/engine'
require 'active_record/acts_as/orderable_table'
require 'active_record/acts_as'
require 'active_admin/orderable_table'
